/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Ring2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ring2(props) {
  const { nodes, materials } = useGLTF('./models/Ring2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, 0.123, 0.008]}>
        <group position={[0, -0.018, -0.001]} scale={11.4}>
          <group scale={0.01}>
            <mesh geometry={nodes.diamond.geometry} material={materials['Material_3.002']} position={[-0.3, -1.307, 19.923]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.ring.geometry} material={materials['metal.001']} position={[-0.3, -1.307, 19.923]} rotation={[-Math.PI / 2, 0, 0]} />
            <group position={[-0.342, 10.309, 4.141]} rotation={[Math.PI, -1.466, Math.PI]} scale={0.007}>
              <mesh geometry={nodes.Mesh_1002.geometry} material={materials['Material_2.002']} />
              <mesh geometry={nodes.Mesh_1002_1.geometry} material={materials['Material_1.002']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Ring2.gltf')
